version: "3"
services:
  node-app:
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment: 
      PORT: 8080
      REDIS_HOST: redis
    networks:
      - schedulerNetwork
    depends_on: 
      - redis
  redis:
    image: "redis"
    ports:
      - "6397:6397"
    networks:
      - schedulerNetwork
    command: ["redis-server", "--bind", "redis", "--port", "6397"]
networks:
  schedulerNetwork: