version: "3"
services:
  node-app:
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment: 
      PORT: 8080
      REDIS_HOST: redis
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_NAME: ${SESSION_NAME}
      COOKIE_MAX_AGE: ${COOKIE_MAX_AGE}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
    depends_on: 
      - redis
  redis:
    image: "redis"
    ports:
      - "6397:6397"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/usr/local/etc/redis/data
    command: ["redis-server", "--bind", "redis", "--port", "6397"]